MLGBrotishka/issue1
MLGBrotishka/yadro-course pull request #3
Opened 2024-03-25 20:43 UTC by MLGBrotishka

Fixes #1
Добавленны 2 флага -s для строки, -n для игнорирования чисел
От апострофов избавляемся, ничего полезного они не несут
Очистка от стоп слов производится сторонней библиотекой, также реализованна своя очистка от стоп-слов, можно расширять.

2024-03-26 07:04 UTC, vbelogrudov commented
все здорово, разве что разобраться с ирландцами и мелкими словами, скажем < 3 букв

2024-03-26 07:05 UTC, vbelogrudov requested changes
ehh, O'Connor!

2024-03-26 07:05 UTC, vbelogrudov commented on main.go
> +	var keys []string
можно однострочник, если добавить x/exp/maps
Очень надеюсь, что все эти функции перенесут в основной пакет maps.

Другой вариант - наполнять слайс, потом его slices.Sort/slices.Compact

2024-03-26 10:55 UTC, vbelogrudov requested changes
➜  yadro-course git:(MLGBrotishka/issue1) ✗ ./myapp -s "O'Connor" 
o

В остальном все можно оставить как есть

2024-03-26 19:14 UTC, MLGBrotishka commented
Обновил pr. Если все ок, то что следующим лучше делать тесты или может поддержку русского)

2024-03-26 22:00 UTC, MLGBrotishka commented
> все здорово, разве что разобраться с ирландцами и мелкими словами, скажем < 3 букв

Про ирландцев не понял, а про мелкие слова, можно ли их просто игнорировать? По идее могут попасться аббревиатуры или еще что-то значимое. В целом расширил стоп слова длиной 1-2 буквы

2024-03-27 08:14 UTC, vbelogrudov approved these changes
все отлично, можно мержить :)

2024-03-27 08:14 UTC, vbelogrudov commented on main.go
> +	words := strings.Fields(cleanedStrings)
как вариант, можно избавиться от апострофов через [ strings.FieldsFunc](https://pkg.go.dev/strings#example-FieldsFunc), re чуть тяжелее и специфичнее. Но вариант рабочий

2024-03-27 08:39 UTC, vbelogrudov commented
> Обновил pr. Если все ок, то что следующим лучше делать тесты или может поддержку русского)

можно в оставшееся всемя посмотреть в тесты и написать бекчмарк. Формально задание выполнено :+1:

2024-03-27 12:55 UTC, merged