Задание_2 #4
MLGBrotishka/yadro-course pull request #5
Opened 2024-04-05 13:17 UTC by MLGBrotishka

#4
Сделал реализацию задания.

2024-04-05 16:14 UTC, vbelogrudov requested changes
привет!

все неплохо, есть замечания :)
1. не обрабатывается "прикол" 404. Из за  этого
```
yadro-course$ ./xkcd
Error fetching comics: invalid character '<' looking for beginning of value

```
2. не учитываются накопленные комиксы из базы данных
3. нет индикации прогресса, например, каждые 100 комиксов, и сохранения промежуточных результатов

2024-04-05 16:14 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	comics, err := client.FetchComics(limit)
здесь стоит уточнить, что флаг -n подразумевался для вывода n записей при флаге -o. А читать из xkcd можно все до конца. Можно в самом клиенте xkcd зашить ограничение для отладки, но необязательно.

2024-04-05 16:14 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +
здесь можно чуть упростить,

err = json.NewDecoder(resp.Body).Decode(&comic)

2024-04-05 16:15 UTC, vbelogrudov requested changes

2024-04-05 16:15 UTC, vbelogrudov commented on pkg/words/normalize.go
> +	"my_app/pkg/xkcd"
в идеале бы нам не привязываться к пакету pkg/xkcd

2024-04-05 21:26 UTC, MLGBrotishka commented on cmd/xkcd/main.go
> +	// Добавляем флаги
Добавил флаг для конфига

2024-04-05 21:26 UTC, MLGBrotishka commented on cmd/xkcd/main.go
> +	comics, err := client.FetchComics(limit)
Исправил флаг для вывода

2024-04-05 21:26 UTC, MLGBrotishka commented on pkg/xkcd/client.go
> +
Согласен, исправил

2024-04-05 21:27 UTC, MLGBrotishka commented on pkg/words/normalize.go
> +	"my_app/pkg/xkcd"
Пока не придумал, как это сделать. Через какой-нибудь comicinterface?

2024-04-05 21:29 UTC, MLGBrotishka commented
> привет!
> 
> все неплохо, есть замечания :)
> 
> 1. не обрабатывается "прикол" 404. Из за  этого
> 
> ```
> yadro-course$ ./xkcd
> Error fetching comics: invalid character '<' looking for beginning of value
> ```
> 
> 2. не учитываются накопленные комиксы из базы данных
> 3. нет индикации прогресса, например, каждые 100 комиксов, и сохранения промежуточных результатов

1 исправил
2 теперь учитывается, можно запустить с флагом -r, чтобы не учитывалось
3 теперь есть и можно задавать размер разбиения фагом -s

2024-04-06 07:36 UTC, vbelogrudov commented on pkg/words/normalize.go
> +	"my_app/pkg/xkcd"
можно остановиться на том, что в words мы кидаем фразы, пусть даже по одной, а получаем списки ключей. words не нужно знать о комиксах

2024-04-06 07:42 UTC, vbelogrudov approved these changes
привет!

почти все работает, можно усовершенствовать в последующих заданиях :)
Из возможных усовершенствований:

1. -f по умолчанию 1
2. -t по умолчанию math.MaxInt
3. мне так и не удалось загрузить больше 403х комиксов, запускал ./xkcd -f 1 -t 10000 -r

2024-04-06 09:38 UTC, MLGBrotishka commented
> привет!
> 
> почти все работает, можно усовершенствовать в последующих заданиях :) Из возможных усовершенствований:
> 
> 1. -f по умолчанию 1
> 2. -t по умолчанию math.MaxInt
> 3. мне так и не удалось загрузить больше 403х комиксов, запускал ./xkcd -f 1 -t 10000 -r

1. Да согласен, не увидел
2. По умолчанию равен 0, что значит без ограничений. Если лучше поменять с 0 на maxInt, могу исправить
3. Я про другое подумал и другое исправил, теперь 404 комикс не рушит загрузку

2024-04-06 09:38 UTC, MLGBrotishka commented on pkg/words/normalize.go
> +	"my_app/pkg/xkcd"
Понял, отделение от комиксов в принципе, исправил

2024-04-07 13:04 UTC, vbelogrudov reviewed
сложновато получилось с кучей флагов, 

yadro-course$ ./xkcd
Loaded new comics:  101

yadro-course$ ./xkcd
Loaded new comics:  0

Как загрузить максимум? Как докачать базу с 100 до 250?

2024-04-07 13:05 UTC, vbelogrudov commented
yadro-course$ ./xkcd -t 250
Loaded new comics:  0

yadro-course$ ./xkcd -t 250 -r
Loaded new comics:  101
Loaded new comics:  202
Loaded new comics:  250

yadro-course$ ./xkcd -t 251
Loaded new comics:  0

yadro-course$ ./xkcd -t 251 -r
Loaded new comics:  101
Loaded new comics:  202
Loaded new comics:  251

2024-04-07 15:13 UTC, MLGBrotishka commented
Запускаю у себя
yadro-course$ ./xkcd -t 250
Loaded new comics:  101
Loaded new comics:  202
Loaded new comics:  250
yadro-course$ ./xkcd -t 250 -r
Loaded new comics:  101
Loaded new comics:  202
Loaded new comics:  250
Проблему с максимумом пофиксил, также как и дозагрузку.
Проверил, теперь все должно быть ок

2024-04-07 15:14 UTC, MLGBrotishka commented
> сложновато получилось с кучей флагов,
> 
> yadro-course$ ./xkcd Loaded new comics: 101
> 
> yadro-course$ ./xkcd Loaded new comics: 0
> 
> Как загрузить максимум? Как докачать базу с 100 до 250?

Максимум загрузить можно если не указывать конечный комикс
Usage of ./xkcd:
  -c string
        Config path
  -f int
        Load from id (default 1)
  -n int
        Limit the number of comics
  -o    Output JSON structure
  -r    Overwrite existing comics
  -s int
        Chunk size load/save (default 99)
  -t int
        Load to id

2024-04-08 07:34 UTC, closed without merging